Repository Team-Sttock/FE, pull requests merged in 2023-11, with the labels that each got.

#36 상품 추가 필드에 리스트박스 추가
  components/ListBox.tsx
  pages/product/add.tsx
Labels: ASK

#37 Refactor : Link 추가 연결, 에러 수정
  components/DatepickerField.tsx
  components/Navbar.tsx
Labels: ASK, Refactor

#38 컴포넌트들에 rules 속성 추가
  components/ComboBox.tsx
  components/DatepickerField.tsx
  components/ListBox.tsx
  pages/product/add.tsx
Labels: SHOW

#39 Feat : 상품 api
  apis/basic.ts
  apis/index.ts
  apis/products.ts
  hooks/auth/mutations/useProducts.ts
Labels: ASK, Feature

#40 모달 컴포넌트 작성
  .pnp.cjs
  .yarn/cache/@toss-use-overlay-npm-1.3.6-38e3e08af6-90c7cf24a9.zip
  .yarn/cache/@types-react-npm-18.2.37-3fa76216da-2d2599f1a0.zip
  components/Modal.tsx
  package.json
  pages/_app.tsx
  yarn.lock
Labels: ASK

#41 인증 연동 및 인가 처리 구현
  apis/auth.ts
  apis/index.ts
  apis/user.ts
  components/Button.tsx
  components/Container.tsx
  components/Navbar.tsx
  hooks/auth/mutations/useCheckCode.ts
  hooks/auth/mutations/useCheckLoginId.ts
  hooks/auth/mutations/useVerifyEmail.ts
  middleware.ts
  next.config.js
  pages/_app.tsx
  pages/calendar.tsx
  pages/index.tsx
  pages/list.tsx
  pages/login.tsx
  pages/product/[pid]/edit-state.tsx
  pages/product/[pid]/index.tsx
  pages/product/add.tsx
  pages/user/join.tsx
  utils/cookie.ts
Labels: ASK
