Repository Team-Sttock/FE, pull requests merged in 2023-09, with the labels that each got.

#19 feature: Button, Input 컴포넌트
  features/common/components/Button.tsx
  features/common/components/Input.tsx
  pages/login.tsx
Labels: ASK, Feature

#21 chore: eslint 룰 수정
  .eslintrc.json
Labels: SHOW

#24 naming-convention 쪽 eslint 룰 변경
  .eslintrc.json
Labels: ASK

#23 feature: datepicker 필드 구현
  .pnp.cjs
  .yarn/cache/@popperjs-core-npm-2.11.8-f1692e11a0-e5c69fdebf.zip
  .yarn/cache/@types-react-datepicker-npm-4.15.0-6db90fe0cc-02a7125b25.zip
  .yarn/cache/classnames-npm-2.3.2-d2fdae468d-2c62199789.zip
  .yarn/cache/react-datepicker-npm-4.17.0-3bb2cbd801-62d40e9526.zip
  .yarn/cache/react-fast-compare-npm-3.2.2-45b585a872-2071415b4f.zip
  .yarn/cache/react-onclickoutside-npm-6.13.0-c9116fb62e-a7cfe62e91.zip
  .yarn/cache/react-popper-npm-2.3.0-1045578379-837111c987.zip
  .yarn/cache/warning-npm-4.0.3-291e921d6d-4f2cb6a957.zip
  features/common/components/DatepickerField.tsx
  package.json
  pages/test.tsx
  styles/globals.css
  yarn.lock
Labels: ASK, Feature

#26 Feature: 상품 detail page 구현 , 헤더 마진 수정
  features/common/components/Navbar.tsx
  pages/detail.tsx
  public/icons/bath-icon.svg
  public/icons/etc-icon.svg
  public/icons/hairbody-icon.svg
  public/icons/kitchen-icon.svg
  public/icons/life-icon.svg
  public/icons/skincare-icon.svg
  public/icons/teeth-icon.svg
  public/icons/women-icon.svg
Labels: ASK, Feature

#27 Refactor : 디테일 페이지 디자인 임의 수정, span component 추가
  pages/detail.tsx
Labels: SHIP, Feature
