Repository Team-Sttock/FE, pull requests merged in 2023-10, with the labels that each got.

#28 회원가입 UI와 state 연결 완료
  features/common/components/DatepickerField.tsx
  pages/register.tsx
Labels: ASK

#29 Feature : edit state page 레이아웃 및 boxshadow config
  features/common/components/DropdownField.tsx
  pages/detail.tsx
  pages/edit-state.tsx
  tailwind.config.js
Labels: SHIP

#30 Feature/add page
  features/common/components/ComboBox.tsx
  features/common/components/DatepickerField.tsx
  features/common/components/Input.tsx
  features/common/components/InputLabel.tsx
  pages/add.tsx
  pages/register.tsx
  pages/test.tsx
Labels: ASK, Feature

#31 Feature: list page 구현
  .pnp.cjs
  .yarn/cache/@babel-runtime-npm-7.23.1-9b8781107c-0cd0d43e6e.zip
  .yarn/cache/rc-progress-npm-3.5.1-ffb1385d31-b0722a6963.zip
  .yarn/cache/rc-util-npm-5.37.0-3702ab79a4-0a72644f09.zip
  features/products/components/Item.tsx
  package.json
  pages/detail.tsx
  pages/index.tsx
  pages/list.tsx
  public/icons/goto.svg
  yarn.lock
Labels: SHOW, Feature

#32 Feature : 아이템 컨테이너, 상태라벨, 필터링 구현
  .pnp.cjs
  .yarn/cache/@headlessui-react-npm-1.7.17-c3f120aed0-0cdb67747e.zip
  features/common/components/Dropdown.tsx
  features/common/components/StateLabel.tsx
  features/products/components/FilteringField.tsx
  features/products/components/Item.tsx
  package.json
  pages/detail.tsx
  pages/edit-state.tsx
  pages/list.tsx
  public/icons/deleteButton.svg
  public/icons/down-arrow-selected.svg
  public/icons/down-arrow.svg
  tailwind.config.js
  yarn.lock
Labels: ASK, Feature

#33 Feature/auth
  .pnp.cjs
  .yarn/cache/@tanstack-query-core-npm-5.0.0-rc.12-ff0767659a-580295da35.zip
  .yarn/cache/@tanstack-react-query-npm-5.0.0-rc.12-001dde9e1b-dd24b1e918.zip
  .yarn/cache/asynckit-npm-0.4.0-c718858525-7b78c451df.zip
  .yarn/cache/axios-npm-1.5.1-6bc68e7d25-4444f06601.zip
  .yarn/cache/combined-stream-npm-1.0.8-dc14d4a63a-49fa4aeb49.zip
  .yarn/cache/delayed-stream-npm-1.0.0-c5a4c4cc02-46fe6e83e2.zip
  .yarn/cache/follow-redirects-npm-1.15.3-ca69c47b72-584da22ec5.zip
  .yarn/cache/form-data-npm-4.0.0-916facec2d-01135bf867.zip
  .yarn/cache/mime-db-npm-1.52.0-b5371d6fd2-0d99a03585.zip
  .yarn/cache/mime-types-npm-2.1.35-dd9ea9f3e2-89a5b7f1de.zip
  .yarn/cache/proxy-from-env-npm-1.1.0-c13d07f26b-ed7fcc2ba0.zip
  apis/auth/postLogin.ts
  apis/client.ts
  apis/user/getCheckEmail.ts
  apis/user/getMe.ts
  apis/user/getUser.ts
  apis/user/postCode.ts
  apis/user/postEmail.ts
  apis/user/postFindLoginId.ts
  apis/user/postPassword.ts
  apis/user/postRecoverPassword.ts
  apis/user/postSignup.ts
  features/auth/mutations/useCheckLoginId.ts
  features/auth/mutations/useEmailCode.ts
  features/auth/mutations/useLogin.ts
  features/auth/mutations/useSignUp.ts
  features/auth/mutations/useVerifyEmail.ts
  package.json
  pages/_app.tsx
  pages/login.tsx
  pages/register.tsx
  yarn.lock
Labels: SHOW

#34 Feat : 캘린더 페이지 구현
  features/products/components/CalendarItem.tsx
  pages/calendar.tsx
  pages/detail.tsx
Labels: SHOW, Feature

#35 코드 리펙토링 + 패스 변경
  apis/auth.ts
  apis/index.ts
  apis/user.ts
  apis/user/getCheckEmail.ts
  apis/user/getMe.ts
  apis/user/getUser.ts
  apis/user/postCode.ts
  apis/user/postEmail.ts
  apis/user/postFindLoginId.ts
  apis/user/postPassword.ts
  apis/user/postRecoverPassword.ts
  apis/user/postSignup.ts
  components/Button.tsx
  components/ComboBox.tsx
  components/DatepickerField.tsx
  components/Dropdown.tsx
  components/Input.tsx
  components/InputLabel.tsx
  components/Navbar.tsx
  components/StateLabel.tsx
  components/products/Calendar.tsx
  components/products/CalendarItem.tsx
  components/products/FilteringField.tsx
  components/products/Item.tsx
  features/auth/hooks/index.ts
  features/auth/utils/index.ts
  features/common/hooks/index.ts
  features/products/hooks/index.ts
  features/products/utils/index.ts
  hooks/auth/mutations/useCheckLoginId.ts
  hooks/auth/mutations/useEmailCode.ts
  hooks/auth/mutations/useLogin.ts
  hooks/auth/mutations/useSignUp.ts
  hooks/auth/mutations/useVerifyEmail.ts
  pages/calendar.tsx
  pages/index.tsx
  pages/list.tsx
  pages/login.tsx
  pages/product/[pid]/edit-state.tsx
  pages/product/[pid]/edit.tsx
  pages/product/[pid]/index.tsx
  pages/product/add.tsx
  pages/user/find-id.tsx
  pages/user/find-password.tsx
  pages/user/join.tsx
  tailwind.config.js
  utils/classNames.ts
Labels: SHOW
